### ISSUE TITLE
lein fighweel - fails to start

### ISSUE THREAD

**Issue by harold** [reagent-project/reagent-frontend-template#16]
Hi, thanks for this project, having a template to quickly setup cljs to test out front-end ideas is great!

I created a new project today with:

```
lein new reagent-frontend cljs-test +figwheel
```

And then tried `lein figwheel`, but got the following error and it did not start up:

```
Figwheel: Cutting some fruit, just a sec ...
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/update-vals
WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/update-keys
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/update-vals
WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/update-keys
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.passes, being replaced by: #'clojure.tools.analyzer.utils/update-vals
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.passes.uniquify, being replaced by: #'clojure.tools.analyzer.utils/update-vals
Figwheel: Validating the configuration found in project.clj
Figwheel: Configuration Valid ;)
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - app
Compiling build :app to "public/js/app.js" from ["src" "env/dev/cljs"]...
Successfully compiled build :app to "public/js/app.js" in 0.361 seconds.
Figwheel: Starting CSS Watcher for paths  ["public/css"]
Figwheel: Starting nREPL server on port: 7002
Launching ClojureScript REPL for build: app
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild id ...)        ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once id ...)             ;; builds source one time
          (clean-builds id ..)            ;; deletes compiled cljs target files
          (print-config id ...)           ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
          (figwheel.client/set-autoload false)    ;; will turn autoloading off
          (figwheel.client/set-repl-pprint false) ;; will turn pretty printing off
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
[Rebel readline] Type :repl/help for online help info
java.io.FileNotFoundException: Could not locate vendor/bridge__init.class, vendor/bridge.clj or vendor/bridge.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:1060)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:1033)
	at rebel_readline.cljs.repl$eval25605$repl_STAR___25606.invoke(repl.clj:77)
	at clojure.lang.Var.invoke(Var.java:388)
	at figwheel_sidecar.repl$eval20357$fn__20358.invoke(repl.clj:218)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at figwheel_sidecar.repl$repl.invokeStatic(repl.clj:346)
	at figwheel_sidecar.repl$repl.doInvoke(repl.clj:344)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at figwheel_sidecar.system$start_figwheel_repl.invokeStatic(system.clj:525)
	at figwheel_sidecar.system$start_figwheel_repl.invoke(system.clj:516)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invokeStatic(system.clj:589)
	at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invoke(system.clj:587)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invokeStatic(system.clj:595)
	at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invoke(system.clj:591)
	at figwheel_sidecar.system$cljs_repl_STAR_.invokeStatic(system.clj:611)
	at figwheel_sidecar.system$cljs_repl_STAR_.invoke(system.clj:602)
	at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:636)
	at figwheel_sidecar.system$start_repl.invoke(system.clj:630)
	at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:634)
	at figwheel_sidecar.system$start_repl.invoke(system.clj:630)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at figwheel_sidecar.system$cljs_repl.invokeStatic(system.clj:644)
	at figwheel_sidecar.system$cljs_repl.doInvoke(system.clj:642)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:156)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:147)
	at figwheel_sidecar.repl_api$launch_from_lein.invokeStatic(repl_api.clj:224)
	at figwheel_sidecar.repl_api$launch_from_lein.invoke(repl_api.clj:216)
	at user$eval21659.invokeStatic(form-init2816361050350365811.clj:1)
	at user$eval21659.invoke(form-init2816361050350365811.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7184)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.Compiler.loadFile(Compiler.java:7591)
	at clojure.main$load_script.invokeStatic(main.clj:475)
	at clojure.main$init_opt.invokeStatic(main.clj:477)
	at clojure.main$init_opt.invoke(main.clj:477)
	at clojure.main$initialize.invokeStatic(main.clj:508)
	at clojure.main$null_opt.invokeStatic(main.clj:542)
	at clojure.main$null_opt.invoke(main.clj:539)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```

I don't know what `vendor` is in this case, so unfortunately I am a bit stuck.

```
$ lein --version
Leiningen 2.9.8 on Java 11.0.15 OpenJDK 64-Bit Server VM
```

Let me know what else I can do or provide to try and help debug.

Thanks again for your time and consideration.

**Comment by yogthos** [comment]
Thanks for the report, looks like the issue was caused by the latest non-snapshot version of figwheel being incompatible with newer dependencies. Looks like bumping it up resolves the issue. As a side note, I would recommend shadow-cljs over fgwheel nowadays mainly because it plays much nicer with the NPM ecosystem.

**Comment by harold** [comment]
Thanks for the quick reply! Glad to be of service. Keep up the good work.
